package interfaz;
import javax.swing.JOptionPane;
import metodos.*;
public class FrmMenuPrincipal extends javax.swing.JFrame {
    //Atributos
    private GestionEleccion gestionEleccion;
    private GestionPartidoPolitico gestionPartido;
    private GestionCandidato gestionCandidato;
    private GestionMesaElectoral gestionMesaElectoral;
    private GestionActaElectoral gestionActa;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName());

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
            gestionEleccion = new GestionEleccion();
            gestionPartido = new GestionPartidoPolitico();
            gestionCandidato = new GestionCandidato();
            gestionMesaElectoral = new GestionMesaElectoral();
            gestionActa = new GestionActaElectoral();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEleccion = new javax.swing.JButton();
        btnPartido = new javax.swing.JButton();
        btnCandidato = new javax.swing.JButton();
        btnMesa = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Menu Principal");

        btnEleccion.setText("Gestion Eleccion");
        btnEleccion.addActionListener(this::btnEleccionActionPerformed);

        btnPartido.setText("Gestion Partidos");
        btnPartido.addActionListener(this::btnPartidoActionPerformed);

        btnCandidato.setText("Gestion Candidatos");
        btnCandidato.addActionListener(this::btnCandidatoActionPerformed);

        btnMesa.setText("Gestion Mesas");
        btnMesa.addActionListener(this::btnMesaActionPerformed);

        btnReporte.setText("Reporte");
        btnReporte.addActionListener(this::btnReporteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEleccion)
                    .addComponent(btnPartido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCandidato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEleccion)
                    .addComponent(btnCandidato))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMesa)
                    .addComponent(btnPartido))
                .addGap(26, 26, 26)
                .addComponent(btnReporte)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleccionActionPerformed
        // TODO add your handling code here:
        FrmEleccion frm = new FrmEleccion(gestionEleccion);
        frm.setVisible(true);
    }//GEN-LAST:event_btnEleccionActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        String reporteTotal = gestionEleccion.generarInforme()
                           + gestionCandidato.generarInforme()
                           + gestionPartido.generarInforme()
                           + gestionMesaElectoral.generarInforme();

    JOptionPane.showMessageDialog(this, reporteTotal);
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidoActionPerformed
        // TODO add your handling code here:
        FrmPartido frm = new FrmPartido(gestionPartido);
        frm.setVisible(true);
    }//GEN-LAST:event_btnPartidoActionPerformed

    private void btnCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandidatoActionPerformed
        // TODO add your handling code here:
        FrmCandidato frm = new FrmCandidato(gestionCandidato);
        frm.setVisible(true);
    }//GEN-LAST:event_btnCandidatoActionPerformed

    private void btnMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesaActionPerformed
        // TODO add your handling code here:
        FrmMesa frm = new FrmMesa(gestionMesaElectoral);
        frm.setVisible(true);
    }//GEN-LAST:event_btnMesaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCandidato;
    private javax.swing.JButton btnEleccion;
    private javax.swing.JButton btnMesa;
    private javax.swing.JButton btnPartido;
    private javax.swing.JButton btnReporte;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
